name: Test Image

on:
  pull_request:
    branches:
      - master

jobs:
  build_and_test_docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2

      - run: make docker
        name: Make Docker

      # Checkout the latest saucectl
      - uses: actions/checkout@v2
        with:
          repository: saucelabs/saucectl
          path: saucectl

      # Build saucectl
      - run: pushd saucectl && make build && popd
        name: Build Saucectl and run E2E tests

      # Run e2e tests (Docker)
      - run: bash ./tests/run.sh
        env:
          SKIP_CI: true
          SAUCE_CTL_BINARY: ./saucectl/saucectl
        name: Build Saucectl and run E2E tests

  build_and_test_local:
    runs-on: windows-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - run: npm ci --production
        name: Install dependencies
      - run: node . --suiteName basic-js --runCfgPath ./tests/fixtures/basic-js/sauce-runner.json
        env:
          SAUCE_VM: true
        name: Run test locally

